"""empty message

Revision ID: 285542f2b8a7
Revises: 14f2bf7f4bcd
Create Date: 2023-12-30 16:18:38.005656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285542f2b8a7'
down_revision = '14f2bf7f4bcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('writer', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
