"""empty message

Revision ID: b3b62619d77d
Revises: ce904d567c8b
Create Date: 2023-12-30 17:27:44.209722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b62619d77d'
down_revision = 'ce904d567c8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
