"""empty message

Revision ID: ce904d567c8b
Revises: 285542f2b8a7
Create Date: 2023-12-30 17:19:58.207308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce904d567c8b'
down_revision = '285542f2b8a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
